#!/bin/bash

# Pattern should contain {X}
# Example 360.mp4:hls:seg-{X}-v1-a1.ts
FILEPATTERN="$1" 
FILENAME="${2:-NewVideo}" 

# ${FILEPATTERN/\{X\}/"*"} code it's a bash code (${parameter/pattern/string}) to replace {X} from pattern by * 
# Cat command concantenate all ts files in one
cat ${FILEPATTERN/\{X\}/"*"} > merged_ts.ts

# Find all .ts files except merged_ts.ts and delete
find . -type f -name '*.ts' -and -not -name 'merged_ts.ts' -delete

# Convert to mp4
ffmpeg -i 'merged_ts.ts' -acodec copy -vcodec copy -bsf:a aac_adtstoasc $FILENAME.mp4